language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore 7in14.sln
 - dotnet test 7in14.Tests/7in14.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info
after_success:
 - bash <(curl -s https://codecov.io/bash)
